
export const projectRoles = {
  'Software Development & IT': [
    'Software Engineer',
    'Frontend Developer',
    'Backend Developer',
    'Full Stack Developer',
    'Mobile Developer',
    'Game Developer',
    'Data Scientist',
    'Machine Learning Engineer',
    'AI Researcher',
    'Cloud Architect',
    'DevOps Engineer',
    'Cybersecurity Specialist',
    'Software Tester',
    'Quality Assurance Engineer',
    'Blockchain Developer',
    'IoT Developer',
    'Database Administrator',
    'System Administrator',
    'Network Engineer',
  ],
  'Engineering & Robotics': [
    'Embedded Systems Engineer',
    'Robotics Engineer',
    'Architect',
  ],
  'Design & Creative Arts': [
    'UI/UX Designer',
    'Graphic Designer',
    '3D Modeler',
    'Animator',
    'Illustrator',
    'Photographer',
    'Art Director',
    'Painter',
    'Sculptor',
    'Ceramicist',
    'Gallery Curator',
    'Tattoo Artist',
    'Interior Designer',
    'Fashion Designer',
    'Costume Designer',
  ],
  'Business & Management': [
    'Product Manager',
    'Project Manager',
    'Business Analyst',
    'Entrepreneur',
    'Business Strategist',
    'Event Planner',
    'Community Manager',
    'Sales Manager',
    'Customer Success Manager',
  ],
  'Marketing & Sales': [
    'Digital Marketing Specialist',
    'SEO Specialist',
    'Content Marketer',
    'Social Media Manager',
  ],
  'Writing & Communication': [
    'Content Writer',
    'Technical Writer',
    'Author',
    'Blogger',
    'Editor',
    'Journalist',
    'Public Speaker',
  ],
  'Audio & Video Production': [
    'Video Editor',
    'Music Producer',
    'Sound Engineer',
    'Podcast Producer',
    'Voice Actor',
    'Documentary Filmmaker',
    'Drone Operator',
  ],
  'Science & Research': [
    'Environmental Scientist',
    'Sustainability Consultant',
    'Healthcare Data Analyst',
    'MedTech Specialist',
    'Research Scientist',
    'Lab Technician',
    'Biotech Engineer',
  ],
  'Education & Training': [
    'Educator',
    'E-learning Developer',
    'Instructional Designer',
    'Culinary Instructor',
  ],
  'Construction & Skilled Trades': [
    'Woodworker',
    'Metalworker',
    'Carpenter',
    'DIY Enthusiast',
    'Home Automation Specialist',
    'Electrician',
    'Plumber',
    'General Contractor',
  ],
  'Health & Wellness': [
    'Fitness Trainer',
    'Nutritionist',
    'Wellness Coach',
    'Yoga Instructor',
    'Sports Coach',
    'Personal Trainer',
    'Art Therapist',
  ],
  'Food & Culinary': [
    'Chef',
    'Sous Chef',
    'Pastry Chef',
    'Event Caterer',
    'Barista',
  ],
  'Agriculture & Environment': [
    'Horticulturist',
    'Gardener',
    'Landscape Designer',
  ],
  Miscellaneous: [],
};
