// roles.ts
export const projectRoles = [
    'Software Engineer',
    'Frontend Developer',
    'Backend Developer',
    'Full Stack Developer',
    'Mobile Developer',
    'Game Developer',
    'Data Scientist',
    'Machine Learning Engineer',
    'AI Researcher',
    'Cloud Architect',
    'DevOps Engineer',
    'Cybersecurity Specialist',
    'UI/UX Designer',
    'Embedded Systems Engineer',
    'Robotics Engineer',
    'Software Tester',
    'Quality Assurance Engineer',
    'Blockchain Developer',
    'IoT Developer',
    'Database Administrator',
    'System Administrator',
    'Network Engineer',
    'Graphic Designer',
    '3D Modeler',
    'Video Editor',
    'Animator',
    'Illustrator',
    'Photographer',
    'Content Writer',
    'Music Producer',
    'Sound Engineer',
    'Art Director',
    'Podcast Producer',
    'Voice Actor',
    'Product Manager',
    'Project Manager',
    'Business Analyst',
    'Digital Marketing Specialist',
    'SEO Specialist',
    'Content Marketer',
    'Social Media Manager',
    'Sales Manager',
    'Customer Success Manager',
    'Entrepreneur',
    'Business Strategist',
    'Event Planner',
    'Community Manager',
    'Environmental Scientist',
    'Sustainability Consultant',
    'Healthcare Data Analyst',
    'MedTech Specialist',
    'Research Scientist',
    'Lab Technician',
    'Biotech Engineer',
    'Educator',
    'E-learning Developer',
    'Instructional Designer',
    'Technical Writer',
    'Author',
    'Blogger',
    'Editor',
    'Public Speaker',
    'Woodworker',
    'Metalworker',
    'Carpenter',
    'DIY Enthusiast',
    'Home Automation Specialist',
    'Electrician',
    'Plumber',
    'General Contractor',
    'Fitness Trainer',
    'Nutritionist',
    'Wellness Coach',
    'Yoga Instructor',
    'Sports Coach',
    'Personal Trainer',
    'Chef',
    'Sous Chef',
    'Pastry Chef',
    'Culinary Instructor',
    'Event Caterer',
    'Barista',
    'Artist',
    'Painter',
    'Sculptor',
    'Ceramicist',
    'Gallery Curator',
    'Art Therapist',
    'Documentary Filmmaker',
    'Journalist',
    'Drone Operator',
    'Architect',
    'Interior Designer',
    'Horticulturist',
    'Gardener',
    'Landscape Designer',
    'Fashion Designer',
    'Costume Designer',
    'Tattoo Artist',
  ];
  