export const projectTags = {
  'Software Development': [
    'Web Development',
    'Mobile App Development',
    'Game Development',
    'Data Analysis',
    'Machine Learning',
    'Artificial Intelligence',
    'Cloud Computing',
    'DevOps',
    'Cybersecurity',
    'Open Source',
  ],
  'Design & Creative Arts': [
    'UI/UX Design',
    '3D Modeling',
    'Graphic Design',
    'Video Production',
    'Photography',
    'Art & Illustration',
  ],
  'Writing & Content Creation': [
    'Content Writing',
    'Digital Marketing',
    'SEO Optimization',
    'Podcasting',
    'Writing & Publishing',
  ],
  'Business & Management': [
    'E-commerce',
    'Finance & FinTech',
    'Entrepreneurship',
    'Business Strategy',
    'Product Management',
    'Event Planning',
    'Community Building',
  ],
  'Science & Technology': [
    'Blockchain',
    'IoT (Internet of Things)',
    'Embedded Systems',
    'Robotics',
    'Software Testing',
    'Healthcare & MedTech',
    'Research & Development',
  ],
  'Education & Social Impact': [
    'Education & E-learning',
    'Social Impact',
    'Public Speaking',
    'Community Building',
  ],
  'Sustainability & Environment': [
    'Sustainability',
    'Environmental Science',
    'Gardening',
  ],
  'Construction & DIY': [
    'Woodworking',
    'Metalworking',
    'DIY (Do It Yourself)',
    'Home Automation',
    'Carpentry',
  ],
  'Culinary & Wellness': [
    'Cooking & Culinary Arts',
    'Fitness & Wellness',
    'Sports & Athletics',
  ],
};
