// tags.ts
export const projectTags = [
    'Web Development',
    'Mobile App Development',
    'Game Development',
    'Data Analysis',
    'Machine Learning',
    'Artificial Intelligence',
    'Cloud Computing',
    'DevOps',
    'Cybersecurity',
    'UI/UX Design',
    '3D Modeling',
    'Graphic Design',
    'Video Production',
    'Photography',
    'Content Writing',
    'Digital Marketing',
    'SEO Optimization',
    'E-commerce',
    'Blockchain',
    'IoT (Internet of Things)',
    'Embedded Systems',
    'Robotics',
    'Software Testing',
    'Open Source',
    'Education & E-learning',
    'Research & Development',
    'Finance & FinTech',
    'Healthcare & MedTech',
    'Social Impact',
    'Sustainability',
    'Environmental Science',
    'Woodworking',
    'Metalworking',
    'DIY (Do It Yourself)',
    'Home Automation',
    'Carpentry',
    'Gardening',
    'Cooking & Culinary Arts',
    'Art & Illustration',
    'Music Production',
    'Podcasting',
    'Writing & Publishing',
    'Event Planning',
    'Entrepreneurship',
    'Business Strategy',
    'Product Management',
    'Public Speaking',
    'Community Building',
    'Fitness & Wellness',
    'Sports & Athletics',
  ];
  